name = "rational-approximation"
version = "0.1.0"
license = "license"
author = "edvino"
maintainer = "edvin.olofsson@matfys.lth.se"
copyright = "Copyright 2025, edvino"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
stdlib = "*"

[[example]]
name = "thiele_sin"
source-dir = "example/thiele_sin"

[[example]]
name = "MTT_cos"
source-dir = "example/MTT_cos"

[[example]]
name = "pade_exp"
source-dir = "example/pade_exp"